### ISSUE TITLE
better overlay image

### ISSUE THREAD

**Issue by docwilmot** [backdrop-contrib/freezeframe#1]
The original code I suggested used the core `arrow-asc.png`, but this was just for convenience for demo. Would be good to design a nicer, bigger overlay image.

**Comment by btopro** [comment]
![2017-10-26_12-26-02](https://user-images.githubusercontent.com/329735/32064783-dbac37c2-ba48-11e7-8f50-13896e6e473d.png)

for increased accessibility (since auto playing gif's are an accessibility issue as well) we made a little play / stop thing (ignore the terrible text label :) )

**Comment by ghost** [comment]
As per https://github.com/backdrop-ops/contrib/issues/223#issuecomment-336343797, I wanted to get the touch screen issues fixed first. But this is definitely something I intend to do.

**Comment by ghost** [comment]
Can't seem to fix touchscreen issue, so added proper overlay here: https://github.com/backdrop-contrib/freezeframe/commit/29d5ecb1ebf940925f07e298a0b058a306e04738

It doesn't use an image so it's themeable (you can style it differently, or add your own image with CSS).
